// npm dependencies
import React, { Component } from 'react';
import axios from 'axios';

/**
 * CLASS COMPONENT 
 * @description     This component gets the user list and its activities.
 */
class Users extends Component {
    /**
     * Constructor for Users Component.
     * @class
     * @param {Object} 	props	Initialization props.
     * @description		Initializes initial state, from props.
     */
    constructor(props) {
        super(props);
        // initialization of state
        this.state = {
            userList: [],
            selectedUser: {},
            time: {
                startTime: '',
                endTime: ''
            },
            showActivity: false
        }
    }

    /**
     * @description This method is called before component mounts
     */
    componentDidMount() {
        this.getUsers();
    }

    /**
     * @description This method gets all the users form API.
     */
    getUsers = async () => {
        const url = 'http://localhost:3001/members';
        const response = await axios.get(url);
        // Setting the updated state.
        this.setState({ userList: response.data });
    }

    /**
     * @description This method gets all the users form API.
     * @param {object} user It carries selected user details.
     */
    setUser = (user) => {
        this.setState({ selectedUser: user })
    }

    /**
     * @description     This method gets the changes occured in input tags.
     * @param {event} e HTML event generated by input tag.
     */
    handleChange = (e) => {
        this.setState({ showActivity: true })
        const selDate = this.constructDate(e.target.value);
        const tempObj = { ...this.state.selectedUser };
        // filtering and saving the activity for seleselected date.
        const selUserActivity = tempObj.activity_periods.filter(item => item.start_time.includes(selDate));
        // chacks if selected date has activities and assigns time.
        if (selUserActivity.length) {
            let obj = {
                startTime: selUserActivity[0].start_time.replace(selDate, ''),
                endTime: selUserActivity[0].end_time.replace(selDate, '')
            }
            this.setState({ time: obj });
        } else {
            let obj = {
                startTime: '',
                endTime: ''
            }
            this.setState({ time: obj })
        }
    }

    /**
     * @description  This method converts the date into the required string format.
     * @param {date} inputDate it carries the selected date from calendar.
     */
    constructDate = (inputDate) => {
        const date = new Date(inputDate);
        const months = ["Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec"];
        const result = months[date.getMonth()] + ' ' + date.getDate() + ' ' + date.getFullYear();
        return result
    }

    render() {
        const { userList, time, showActivity } = this.state;
        return (
            <div>
                <div className="user-container">
                    <h5 style={{ textAlign: "center" }}>User Activities</h5>
                    <hr />
                    {
                        (userList.length)
                            ? userList.map(user => {
                                return (
                                    <div key={user.id}>
                                        <p className="hover-cls">
                                            <strong> {user.real_name}</strong>
                                            <span>
                                                <button
                                                    className="btn btn-outline-info btn-sm"
                                                    style={{ float: "right" }}
                                                    onClick={() => this.setUser(user)}
                                                    data-toggle="modal"
                                                    data-target="#myModal">
                                                    Get Activities
                                                </button>
                                            </span>
                                        </p>
                                    </div>
                                )
                            })
                            : null
                    }
                </div>
                <div className="modal" id="myModal">
                    <div className="modal-dialog">
                        <div className="modal-content">
                            <div className="modal-body">
                                <h5>Get activities by date</h5>
                                <hr/>
                                <div className="form-group">
                                    <label htmlFor="date">Select the date</label>
                                    <input
                                        type="date"
                                        id="date"
                                        className="form-control"
                                        name="selectedDate"
                                        onChange={this.handleChange}
                                    />
                                </div>
                                <div >
                                    {
                                        (showActivity)
                                            ? <div className="data-cls">
                                                <p>START TIME : <strong>{time.startTime || 'No Activity Found'}</strong></p>
                                                <p>END TIME : <strong>{time.endTime || 'No Activity Found'}</strong></p>
                                            </div>
                                            : null
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}

export default Users;